### ISSUE TITLE
support for STM32L CPU

### ISSUE THREAD

**Issue by seamaster101** [thomasonw/NMEA2000_avr#1]
Hi Al,
I'm working on digital compass project and I have selected Butterfly STM32L board from  here:
[https://www.tindie.com/products/TleraCorp/butterfly-stm32l433-development-board/](url)
the compass is tilt compensated output of yaw, pitch, roll and ROT. It will have NMEA0183, NMEA200, and sine/cosine analog outputs simultaneously.  
I got everything running on Teensy3.2, but i need the 2 DAC outputs from the butterfly board for sine/cosine output. 
I was wondering if this Butterfly STM32L architecture could be easily supported?
thank you!

**Comment by thomasonw** [comment]
Dup of:  [https://github.com/thomasonw/NMEA2000_mbed/issues/1](https://github.com/thomasonw/NMEA2000_mbed/issues/1  )   See link for answer...
